export { default as Intro } from "./intro"
export { default as SkillsTools } from "./skillstools"
export { default as WorkExperience } from "./workexperience"
export { default as Picture } from "./picture"
export { default as ValuesHobbies } from "./valueshobbies"
